import {
  IconHome2,
  IconBuildingSkyscraper,
  IconBuilding,
  IconStairs,
  IconRulerMeasure,
  IconCompass,
  IconRoad,
  IconAirConditioning,
  IconElevator,
  IconShieldCheck,
  IconPlant2,
  IconWindow,
  IconToolsKitchen2,
  IconArmchair2,
  IconBatteryCharging,
  IconSolarPanel,
  IconBucket,
  IconFlame,
  IconSparkles,
  IconStarFilled,
  IconCertificate,
  IconCircleCheck,
  IconKey,
  IconClock,
  IconFileDescription,
  IconArchive,
  IconUserCheck,
  IconTrendingDown,
  IconHandTwoFingers,
  IconCashBanknote,
  IconDoor,
  IconCrown,
  IconBuildingEstate,
  IconLayoutGrid,
  IconBuildingCommunity,
  IconParkingCircle,
  IconArrowsHorizontal,
  IconFileCheck,
  IconChartArea,
  IconCalendar,
  IconUsers,
  IconTrees,
  IconSearch,
  IconMenu2,
  IconX,
  IconChevronDown,
  IconChevronRight,
  IconChevronLeft,
  IconArrowRight,
  IconArrowLeft,
  IconPlus,
  IconMinus,
  IconCheck,
  IconCircleX,
  IconAlertCircle,
  IconInfoCircle,
  IconMail,
  IconPhone,
  IconMessage,
  IconHelp,
  IconWorld,
  IconShield,
  IconBriefcase,
  IconHeart,
  IconSend,
  IconTicket,
  IconFileText,
  IconScale,
  IconClipboardList,
  IconLogin,
  IconLogout,
  IconUser,
  IconStar,
  IconQuote,
  IconMaximize,
  IconNavigation,
  IconBath,
  IconCar,
  IconArmchair,
  IconLoader,
  IconFilter,
  IconGridDots,
  IconList,
  IconMap,
  IconEye,
  IconEyeOff,
  IconCamera,
  IconVideo,
  IconLink,
  IconExternalLink,
  IconDownload,
  IconUpload,
  IconTrash,
  IconEdit,
  IconCirclePlus,
  IconCircleMinus,
  IconRefresh,
  IconSettings,
  IconBell,
  IconHome,
  IconBookmark,
  IconShare,
  IconMapPin,
  IconBolt,
  IconDroplets,
  IconDroplet,
  IconAdjustmentsHorizontal,
  IconArrowsLeftRight,
  IconChartPie,
  IconAlertTriangle,
  IconClock2,
  IconTrendingUp,
  IconSignature,
  IconBuildingCastle,
  IconBed,
  IconChefHat,
  IconCookie,
  IconWallet,
  IconLock,
  IconMessageCircle,
  IconPhoneCall,
  IconLayersSelected,
  IconGridPattern,
  IconBuildingStore,
  IconCash,
  IconCooker,
  IconSchool,
  IconLeaf,
  IconActivity,
  IconAnchor,
  IconFileSearch,
  IconBox,
  IconTree,
  IconWind,
  IconThermometer,
  IconShirt,
  IconSquareCheck,
  IconWifi,
  IconPlug,
  IconPaw,
  IconTractor,
  IconSofa,
  IconPool,
  IconBarbell,
  IconWash,
  IconPlant,
  IconResize,
} from "@tabler/icons-react";

export const PropertyTypeIcons = {
  house: IconHome2,
  apartment: IconBuildingSkyscraper,
  land: IconBuilding,
  bungalow: IconHome2,
  villa: IconBuildingEstate,
  townhouse: IconBuildingCommunity,
  duplex: IconBuildingCommunity,
  penthouse: IconCrown,
  studio: IconLayoutGrid,
  commercial: IconBuildingSkyscraper,
  office: IconBuildingSkyscraper,
  agricultural: IconTractor,
  residential_plot: IconBuilding,
  commercial_plot: IconBuildingSkyscraper,
} as const;

export const PropertyDetailIcons = {
  bedroom: IconBed,
  bathroom: IconBath,
  bathroom_alt: IconBath,
  kitchen: IconChefHat,
  floors: IconStairs,
  total_area: IconRulerMeasure,
  built_up_area: IconChartArea,
  carpet_area: IconMaximize,
  plot_dimensions: IconRulerMeasure,
  build_year: IconCalendar,
  facing: IconCompass,
  road_access: IconRoad,
  parking: IconCar,
  frontage: IconArrowsHorizontal,
  title_status: IconFileCheck,
  water: IconDroplets,
  electricity: IconBolt,
  balcony: IconWindow,
  lift: IconElevator,
  furnishing: IconArmchair2,
  sub_type: IconFileCheck,
  usage_type: IconFileCheck,
  zoning: IconFileCheck,
  corner_plot: IconCertificate,
  plot_shape: IconRulerMeasure,
  bath: IconBath,
  layers: IconLayersSelected,
} as const;

export const AmenityIcons = {
  pool: IconPool,
  parking: IconCar,
  garage: IconParkingCircle,
  gym: IconBarbell,
  wifi: IconWifi,
  air_conditioning: IconAirConditioning,
  heating: IconFlame,
  elevator: IconElevator,
  security: IconShieldCheck,
  garden: IconPlant2,
  balcony: IconWindow,
  terrace: IconWindow,
  kitchen: IconToolsKitchen2,
  furnished: IconArmchair2,
  laundry: IconWash,
  pet_friendly: IconPaw,
  backup_power: IconBatteryCharging,
  solar: IconSolarPanel,
  water_tank: IconBucket,
  fireplace: IconFlame,
  storage: IconBox,
  servant_quarters: IconUsers,
  garden_lawn: IconTrees,
  boundary_wall: IconShield,
  gated_community: IconShieldCheck,
  cooking: IconCooker,
  couch: IconSofa,
  plant: IconPlant,
  camera: IconCamera,
} as const;

export const StatusIcons = {
  featured: IconFlame,
  new: IconSparkles,
  verified: IconCertificate,
  sold: IconCircleCheck,
  rented: IconKey,
  pending: IconClock,
  draft: IconFileDescription,
  archived: IconArchive,
  owner_approved: IconUserCheck,
  price_drop: IconTrendingDown,
  negotiable: IconHandTwoFingers,
  cash_only: IconCashBanknote,
  open_house: IconDoor,
  exclusive: IconCrown,
  just_listed: IconSparkles,
  premium: IconCrown,
  investment: IconTrendingDown,
  heritage: IconFileCheck,
  smart_home: IconBatteryCharging,
  corner: IconCertificate,
  mountain_view: IconSparkles,
  commercial: IconBuildingSkyscraper,
  farmhouse: IconPlant2,
  affordable: IconCashBanknote,
  family_home: IconHome2,
  for_rent: IconKey,
  value_pick: IconCertificate,
} as const;

export const UIIcons = {
  search: IconSearch,
  menu: IconMenu2,
  close: IconX,
  chevronDown: IconChevronDown,
  chevronRight: IconChevronRight,
  chevronLeft: IconChevronLeft,
  arrowRight: IconArrowRight,
  arrowLeft: IconArrowLeft,
  plus: IconPlus,
  minus: IconMinus,
  check: IconCheck,
  error: IconCircleX,
  warning: IconAlertTriangle,
  info: IconInfoCircle,
  mail: IconMail,
  phone: IconPhone,
  message: IconMessage,
  help: IconHelp,
  globe: IconWorld,
  shield: IconShield,
  users: IconUsers,
  briefcase: IconBriefcase,
  heart: IconHeart,
  send: IconSend,
  ticket: IconTicket,
  file: IconFileText,
  scale: IconScale,
  clipboard: IconClipboardList,
  login: IconLogin,
  logout: IconLogout,
  user: IconUser,
  star: IconStar,
  quote: IconQuote,
  maximize: IconResize,
  layers: IconNavigation,
  navigation: IconRoad,
  armchair: IconArmchair,
  compass: IconCompass,
  building: IconBuilding,
  loader: IconLoader,
  filter: IconAdjustmentsHorizontal,
  grid: IconGridDots,
  list: IconList,
  map: IconMap,
  eye: IconEye,
  eyeOff: IconEyeOff,
  camera: IconCamera,
  video: IconVideo,
  link: IconLink,
  externalLink: IconExternalLink,
  download: IconDownload,
  upload: IconUpload,
  trash: IconTrash,
  edit: IconEdit,
  plusCircle: IconCirclePlus,
  minusCircle: IconCircleMinus,
  refresh: IconRefresh,
  settings: IconSettings,
  bell: IconBell,
  home: IconHome,
  bookmark: IconBookmark,
  share: IconShare,
  favorite: IconHeart,
  mapPin: IconMapPin,
  zap: IconBolt,
  droplet: IconDroplet,
  droplets: IconDroplets,
  slidersHorizontal: IconAdjustmentsHorizontal,
  arrowLeftRight: IconArrowsLeftRight,
  pieChart: IconChartPie,
  checkCircle: IconCircleCheck,
  alertCircle: IconAlertCircle,
  clock: IconClock2,
  trendingUp: IconTrendingUp,
  fileSignature: IconSignature,
  landmark: IconBuildingCastle,
  checkCircle2: IconCircleCheck,
  bedDouble: IconBed,
  chefHat: IconChefHat,
  grid2X2: IconGridPattern,
  car: IconCar,
  calendar: IconCalendar,
  cookie: IconCookie,
  wallet: IconWallet,
  checkSquare: IconSquareCheck,
  store: IconBuildingStore,
  banknote: IconCash,
  layoutGrid: IconLayoutGrid,
  doorOpen: IconDoor,
  utensilsCrossed: IconCooker,
  graduationCap: IconSchool,
  leafyGreen: IconLeaf,
  activity: IconActivity,
  anchor: IconAnchor,
  fileSearch: IconFileSearch,
  box: IconBox,
  palmTree: IconTree,
  wind: IconWind,
  thermometer: IconThermometer,
  shirt: IconShirt,
  lock: IconLock,
  messageCircle: IconMessageCircle,
  phoneCall: IconPhoneCall,
  bath: IconBath,
} as const;

export const Icons = {
  ...PropertyTypeIcons,
  ...PropertyDetailIcons,
  ...AmenityIcons,
  ...StatusIcons,
  ...UIIcons,
} as const;

export type IconName = keyof typeof Icons;
